[phases.setup]
nixPkgs = [
  "chromium",
  "glib",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "expat",
  "libdrm",
  "libxkbcommon",
  "pango",
  "cairo",
  "alsa-lib",
  "at-spi2-atk",
  "at-spi2-core",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "gtk3"
]

[phases.build]
cmds = ["npm ci"]

[start]
cmd = "PUPPETEER_EXECUTABLE_PATH=$(which chromium) node server.js"
